name:                data-modeling-and-design
version:             0.1.0.0
github:              "githubuser/data-modeling-and-design"
license:             BSD-3-Clause
author:              "Darren Kim"
maintainer:          "darren.minsoo.kim@gmail.com"

extra-source-files:
- README.md

dependencies:
- base >= 4.7 && < 5
- regex-posix

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src

executables:
  data-modeling-and-design-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - data-modeling-and-design
